redmine:
  image: redmine
  links:
    - dbms:postgres
  ports:
    - "3000:3000"
  volumes:
    - /var/lib/redmine:/usr/src/redmine/files
dbms:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=redmine
